#!/usr/bin/env python3
"""Build two independent stdlib-only executables from shared sources."""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ASSETS = {"INDEX_HTML": "index.html", "STYLES_CSS": "styles.css", "APP_JS": "app.js"}


def build(output: Path, *, tui=False) -> Path:
    core = (ROOT / "src/piluli_core.py").read_text(encoding="utf-8")
    entry = (ROOT / "src" / ("pilulit.py" if tui else "piluli.py")).read_text(encoding="utf-8")
    lines = [line for line in entry.splitlines() if not line.startswith("#!") and line != "from __future__ import annotations" and not line.endswith("# build:core")]
    if not tui:
        for variable, name in ASSETS.items():
            prefix = f"EMBEDDED_{variable} = None"
            index = next(i for i, line in enumerate(lines) if line.startswith(prefix))
            content = (ROOT / "web" / name).read_text(encoding="utf-8")
            lines[index] = f"EMBEDDED_{variable} = {content!r}"
    program = "#!/usr/bin/env python3\n# Generated by build.py; edit src/ and web/, not this file.\n" + core + "\n" + "\n".join(lines) + "\n"
    compile(program, str(output), "exec")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(program, encoding="utf-8")
    output.chmod(0o755)
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "dist/piluli.py", help="Web output")
    parser.add_argument("--tui-output", type=Path, default=ROOT / "dist/pilulit.py", help="TUI output")
    args = parser.parse_args()
    if args.output.resolve() == args.tui_output.resolve():
        parser.error("Output paths must differ")
    for path, tui in ((args.output, False), (args.tui_output, True)):
        result = build(path, tui=tui)
        print(f"Built {result} ({result.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
